### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by afonsopacifer** [afonsopacifer/react-comments#1]
- [ ] Refactor all CSS
- [ ] Add autoprefixer
- [x] Refactor the index.html (insert meta for share, etc...)
- [ ] Remove  Jquery
- [x] Add Lisence and other basic files
- [x] Organize src/ folder
- [x] Update package.json
